// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HttpHeader {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageHint {
    #[prost(string, tag = "1")]
    pub bucket: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key_prefix: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProxyHint {
    #[prost(string, tag = "1")]
    pub primary_pool: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub fallbacks: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskAttributes {
    #[prost(map = "string, string", tag = "1")]
    pub tags: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "2")]
    pub checksum_hint: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mime_hint: ::prost::alloc::string::String,
    /// optional serialized blob
    #[prost(bytes = "vec", tag = "4")]
    pub extra: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownloadTask {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub job_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub resource_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub url: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub headers: ::prost::alloc::vec::Vec<HttpHeader>,
    #[prost(message, optional, tag = "6")]
    pub proxy_hint: ::core::option::Option<ProxyHint>,
    #[prost(message, optional, tag = "7")]
    pub storage_hint: ::core::option::Option<StorageHint>,
    #[prost(message, optional, tag = "8")]
    pub attributes: ::core::option::Option<TaskAttributes>,
    #[prost(string, tag = "9")]
    pub manifest_key: ::prost::alloc::string::String,
    #[prost(uint32, tag = "10")]
    pub attempt: u32,
    #[prost(string, tag = "11")]
    pub tenant: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub trace_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatus {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub job_type: ::prost::alloc::string::String,
    #[prost(enumeration = "JobState", tag = "3")]
    pub state: i32,
    #[prost(uint32, tag = "4")]
    pub resources_total: u32,
    #[prost(uint32, tag = "5")]
    pub resources_completed: u32,
    #[prost(uint32, tag = "6")]
    pub resources_failed: u32,
    #[prost(string, tag = "7")]
    pub manifest_key: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub tenant: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub last_error_code: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub last_error_message: ::prost::alloc::string::String,
    #[prost(uint64, tag = "11")]
    pub log_offset: u64,
    #[prost(uint64, tag = "12")]
    pub timestamp_ms: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobLog {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub resource_id: ::prost::alloc::string::String,
    #[prost(enumeration = "LogLevel", tag = "3")]
    pub level: i32,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "5")]
    pub fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(uint64, tag = "6")]
    pub timestamp_ms: u64,
    #[prost(string, tag = "7")]
    pub trace_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeadLetterTask {
    #[prost(message, optional, tag = "1")]
    pub task: ::core::option::Option<DownloadTask>,
    #[prost(string, tag = "2")]
    pub failure_code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub failure_message: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub attempts: u32,
    #[prost(uint64, tag = "5")]
    pub failed_at_ms: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JobState {
    Unknown = 0,
    Queued = 1,
    InProgress = 2,
    Partial = 3,
    Completed = 4,
    Failed = 5,
}
impl JobState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "JOB_STATE_UNKNOWN",
            Self::Queued => "JOB_STATE_QUEUED",
            Self::InProgress => "JOB_STATE_IN_PROGRESS",
            Self::Partial => "JOB_STATE_PARTIAL",
            Self::Completed => "JOB_STATE_COMPLETED",
            Self::Failed => "JOB_STATE_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOB_STATE_UNKNOWN" => Some(Self::Unknown),
            "JOB_STATE_QUEUED" => Some(Self::Queued),
            "JOB_STATE_IN_PROGRESS" => Some(Self::InProgress),
            "JOB_STATE_PARTIAL" => Some(Self::Partial),
            "JOB_STATE_COMPLETED" => Some(Self::Completed),
            "JOB_STATE_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LogLevel {
    Trace = 0,
    Debug = 1,
    Info = 2,
    Warn = 3,
    Error = 4,
}
impl LogLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Trace => "LOG_LEVEL_TRACE",
            Self::Debug => "LOG_LEVEL_DEBUG",
            Self::Info => "LOG_LEVEL_INFO",
            Self::Warn => "LOG_LEVEL_WARN",
            Self::Error => "LOG_LEVEL_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOG_LEVEL_TRACE" => Some(Self::Trace),
            "LOG_LEVEL_DEBUG" => Some(Self::Debug),
            "LOG_LEVEL_INFO" => Some(Self::Info),
            "LOG_LEVEL_WARN" => Some(Self::Warn),
            "LOG_LEVEL_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
